### ISSUE TITLE
On Documentation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jkkummerfeld/berkeley-coreference-analyser#1]
```
Hi, 

  I am trying to use coreference_reading script for parsing coreference annotated file in CoNLL format. I would like to know what the function read_conll_coref() returns. Can you please help me with this ? If there is some documentation available of the whole system it would be great.

Thanks,
Joe
```

Original issue reported on code.google.com by `joech...@gmail.com` on 13 Dec 2014 at 6:59

**Comment by jkkummerfeld** [comment]
(the author of this issue contacted me via email before I saw this issue, I'm including my response below to avoid this issue https://xkcd.com/979/ )

 There is no documentation aside from the simple instructions for running the code. To read a file I would suggest using read_conll_doc, which takes a filename, and reads in various fields depending on what you set to true. The function itself has some notes on what it returns, though I would say the best way to see how it works is to look at how it is used.

 To directly answer your question, the read_conll_coref function returns a tuple containing information on mentions and clusters:

Mentions - a dictionary
key - (sentence number, start token number, end token number + 1)
value - cluster ID

Clusters - a dictionary that is the reverse mapping of mentions, ie
key - cluster ID
value - a list of (sentence, start, end +1) tuples
